package oop.extra03.enums;

public enum Department {
    APPLIED_LINGUISTICS,
    APLLIED_SOCIAL_SCIENCE,
    ELECTRICAL_ENGINEERING,
    HORTICULTURE,
    MATHEMATICS_INFORMATICS,
    MECHANICAL_ENGINEERING
}
